#!/usr/bin/env bash
# config redirection
sudo apt update
sudo apt install -y nginx

#Nginx redir
sudo sed -i '/^\tserver_name.*/a \\n\trewrite ^\/redirect_me/$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Change response
echo "Hello World" | tee /var/www/html/index.nginx-debian.html

sudo service nginx restart