#!/usr/bin/env bash
# configure a brand new server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i '/# as directory, then fall back to displaying a 404./a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
