#!/usr/bin/env bash
# Installs HAProxy in load balancer

sudo apt-get update -y
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update -y
sudo apt-get install -y haproxy=2.0\*
printf "\nENABLED=1\n" | sudo tee -a /etc/default/haproxy

printf "\nfrontend threebeans.tech\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 2520-web-01 35.237.231.11:80 check\n\tserver 2520-web-02 35.231.46.156:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
