#!/usr/bin/env bash
# configure load balanceer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 2520-web-01 35.237.231.11:80 check\n\tserver 2520-web-02 35.231.46.156:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
