#!/usr/bin/env bash
# Bash script that:
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds


sudo touch /var/run/holbertonscript.pid
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
done