#!/usr/bin/env bash
#   loops from 1 to 10
PROMPT="Best School"
COUNT=1
while [ $COUNT -le 10 ]; do
    if [ $COUNT == 4 ]; then
    echo "bad luck"
    elif [ $COUNT == 8 ]; then
    echo "good luck"
    else
    echo "$PROMPT"
    fi
    COUNT=$((COUNT + 1))
done